# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hFgjSg4gdr1T9VOt3sS5RAim02SZEqVt
"""

class BoardingPass:
    def __init__(self, seat_number, boarding_time, gate, flight_number, passenger_name, departure_city, destination_city, departure_date, arrival_time, terminal):
        self._seat_number = seat_number
        self._boarding_time = boarding_time
        self._gate = gate
        self._flight_number = flight_number
        self._passenger_name = passenger_name
        self._departure_city = departure_city
        self._destination_city = destination_city
        self._departure_date = departure_date
        self._arrival_time = arrival_time
        self._terminal = terminal
        self._availability = True  # Assuming all seats are initially available

    def seat_number(self):
        return self._seat_number

    def boarding_time(self):
        return self._boarding_time

    # Other getter and setter methods for attributes can be added here

    def book_seat(self, passenger_name):
        """
        Book the seat for a passenger.

        Args:
            passenger_name (str): The name of the passenger booking the seat.
        """
        if self._availability:
            self._passenger_name = passenger_name
            self._availability = False
            print(f"Seat {self._seat_number} booked for passenger {passenger_name}.")
        else:
            print(f"Seat {self._seat_number} is already booked.")

    def availability(self):
        return self._availability

    def set_availability(self, value):
        self._availability = value

# Example usage
if __name__ == "__main__":
    # Create a boarding pass instance
    boarding_pass = BoardingPass(seat_number="09A", boarding_time="11:20", gate="03", flight_number="NA4321",
                                 passenger_name="Maryam Matar", departure_city="Chicago ORD", destination_city="New York JFK",
                                 departure_date="06 DEC 20", arrival_time="13:30", terminal="2")

    # Check the availability before booking
    print("Availability before booking:", boarding_pass.availability())

    # Book the seat for a passenger
    boarding_pass.book_seat("Maryam Matar")

    # Check the availability after booking
    print("Availability after booking:", boarding_pass.availability())

class Passenger:
    def __init__(self, name, electronic_ticket):
        self.name = name
        self.electronic_ticket = electronic_ticket

class Flight:
    def __init__(self, flight_number, departure_city, destination_city, departure_date, boarding_time, arrival_time, terminal, gate):
        self.flight_number = flight_number
        self.departure_city = departure_city
        self.destination_city = destination_city
        self.departure_date = departure_date
        self.boarding_time = boarding_time
        self.arrival_time = arrival_time
        self.terminal = terminal
        self.gate = gate

class BoardingPass:
    def __init__(self, seat, boarding_time, gate, flight, passenger):
        self.seat = seat
        self.boarding_time = boarding_time
        self.gate = gate
        self.flight = flight
        self.passenger = passenger

class Seat:
    def __init__(self, seat_number, availability=True):
        self.seat_number = seat_number
        self.availability = availability

# Create objects
passenger = Passenger(name="Maryam matar", electronic_ticket="629")
flight = Flight(flight_number="NA4321", departure_city="CHICAGO ORD", destination_city="NEW YORK JFK", departure_date="06 DEC 20",
                boarding_time="11:20", arrival_time="13:30", terminal="2", gate="03")
seat = Seat(seat_number="09A")
boarding_pass = BoardingPass(seat=seat, boarding_time="11:40", gate="03", flight=flight, passenger=passenger)

# Display boarding pass details
print("Passenger:", boarding_pass.passenger.name)
print("From:", flight.departure_city)
print("Flight:", flight.flight_number)
print("Gate:", boarding_pass.gate)
print("Date:", flight.departure_date)
print("Boarding till:", boarding_pass.boarding_time)
print("Electronic ticket:", passenger.electronic_ticket)
print("Time:", flight.arrival_time)
print("Seat:", boarding_pass.seat.seat_number)
print("To:", flight.destination_city)
print("Arrival time:", flight.arrival_time)
print("Terminal:", flight.terminal)